# Generated by Django 3.2 on 2023-05-15 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0006_auto_20230515_2023"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genretitle",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reviews.genre",
            ),
        ),
    ]
