# Generated by Django 3.2 on 2023-05-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20230515_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
